Update patch set 22
Patch Set 22: Code-Review-1

http://pnexus.sytes.net:8082/61/55461/22/check/contrail-sanity-centos7-k8s/c7bfe58/container-logs/kolla-aio/webui_web_1.log

/usr/src/contrail/contrail-web-core/node_modules/redis/index.js:541
            throw err;
                  ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/src/contrail/contrail-web-controller/webroot/common/api/adminapi.helper.js:19:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Patch-set: 22
Reviewer: Gerrit User 437 <437@c72cd27d-1743-4a55-84a4-cd13b8400c52>
Label: Code-Review=-1